name: Build and Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build Executable
        run: npx electron-builder --win

      - name: Create GitHub Release and Upload Exe
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.1.0
          name: Cinder Client v1.1.0
          draft: false
          prerelease: false
          files: |
            dist/*.exe
            dist/*.yml
            dist/*.blockmap
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
